name: MSDO
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]

jobs:
  sample:
    name: Microsoft Security DevOps
    runs-on: windows-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write

    steps:
      # Checkout your code repository to scan
      - uses: actions/checkout@v3

      # Run MSDO analyzers (IaC misconfigurations)
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: msdo
        with:
          categories: 'IaC'
          tools: 'checkov,terrascan'

      # Install Trivy CLI manually (v0.67.0)
      - name: Install Trivy CLI v0.67.0
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/aquasecurity/trivy/releases/download/v0.67.0/trivy_0.67.0_windows-64bit.zip" -OutFile trivy.zip
          Expand-Archive trivy.zip -DestinationPath $env:USERPROFILE\trivy
          echo "$env:USERPROFILE\trivy" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # Confirm Trivy version (separate step so PATH is reloaded)
      - name: Check Trivy version
        shell: pwsh
        run: trivy --version

      # Run Trivy explicitly in filesystem mode for secret scanning
      - name: Run Trivy for secrets in IaC
        shell: pwsh
        run: |
          trivy fs `
            --scanners secret `
            --severity MEDIUM,HIGH,CRITICAL `
            --ignore-unfixed `
            --format sarif `
            --output trivy-secrets.sarif .

      # Upload MSDO results to Security tab (requires GHAS / Defender for DevOps)
      - name
