name: MSDO
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]

jobs:
  sample:
    name: Microsoft Security DevOps
    runs-on: windows-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write

    steps:
      # Checkout your code repository to scan
      - uses: actions/checkout@v3

      # Run MSDO analyzers (IaC misconfigurations)
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: msdo
        with:
          categories: 'IaC'
          tools: 'checkov,terrascan'

      # Run Trivy explicitly in filesystem mode for secret scanning
      - name: Run Trivy for secrets in IaC
        uses: aquasecurity/trivy-action@v0.11.1
        with:
          scan-type: 'fs'
          scanners: 'secret'
          severity: 'MEDIUM,HIGH,CRITICAL'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-secrets.sarif'

      # Upload MSDO results to Security tab (requires GHAS / Defender for DevOps)
      - name: Upload MSDO alerts to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      # Upload Trivy secret scan results to Security tab
      - name: Upload Trivy secret scan
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-secrets.sarif
